### ISSUE TITLE
URL field content deleted when deactivating the plugin

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/custom-content-portfolio#17] opened 2016-09-26 19:30 UTC
I noticed weird issue. When I deactivate and activate the plugin, URL field meta info gets deleted. All other fields seems to be there.

I only tested this on two multisite installs.

**Comment by justintadlock** [comment] 2016-10-17 18:24
I haven't been able to reproduce this.  However, I'm on a newer version.  I plan to push that live soon.

**Comment by justintadlock** [comment] 2016-11-14 14:41
I'm going to close this one as fixed for the moment.  Let me know if you're still having the issue on the dev copy and I can reopen.

**Comment by djrmom** [comment] 2016-11-14 22:33
I just upgraded to 2.0.0 and tested this and I see the same issue.  I would think this https://github.com/justintadlock/custom-content-portfolio/blob/master/portfolio.php#L246 would be the problem.

**Comment by justintadlock** [comment] 2016-11-14 22:44
Oh, I see now.  Yep, the two meta keys are backwards.

**Comment by justintadlock** [comment] 2016-11-14 22:58
All right.  Now it should actually be fixed. :) I just pushed 2.0.1 live since this will be a breaking issue on sites that are upgrading.

I imagine it hasn't been an issue for most because of no updates since that code was added, so most users wouldn't have deactivated and reactivated the plugin.

**Closed by justintadlock** 2016-11-14 22:58 UTC
